import { test, expect } from '@playwright/test';
import tags from '../test-data/tags.json'; //separate the test data from the test code, and import it as a JSON object. This makes it easier to manage and update the test data, and also allows for reusability across multiple tests.
import authState from '../playwright/.auth/user.json' //importing the object that stores the login session data

test('Mocking API', async ({ page }) => { // useful for testing the UI without relying on the backend, or for testing how the UI behaves with different API responses. 
  await page.route('*/**/api/tags', async route => { //* matches any URL that ends with /api/tags, regardless of the domain or path before it.

    await route.fulfill({ json: tags }); //Use json o send the response as JSON, and body to send the response body as a string. In this case, we are sending the tags object as a JSON response.
  });

  await page.route('*/**/api/articles*', async route => {
    const response = await route.fetch()
    const responseJSON = await response.json()
    responseJSON.articles[0].title = 'This is a mocked article title'
    responseJSON.articles[0].description = 'This is a mocked article description'
    await route.fulfill({ json: responseJSON });
  });

  await page.goto('https://conduit.bondaracademy.com')
  await expect(page.locator('.navbar-brand')).toHaveText(/conduit/)
  await expect(page.locator('.sidebar .tag-pill')).toContainText(['Automation', 'Playwright'])
  await expect(page.locator('.preview-link h1').first()).toContainText('This is a mocked article title')
  await expect(page.locator('.preview-link p').first()).toContainText('This is a mocked article description')
});

test('Delete article', async ({ page, request }) => {

  const token = authState.origins[0].localStorage[0].value //getting the token session value from the user.json generated by the test setup

  const newArticleResponse = await request.post('https://conduit-api.bondaracademy.com/api/articles/', {
    data: {
      "article": {
        "title": "Test title",
        "description": "Test description",
        "body": "Test body",
        "tagList": []
      }
    },
    headers: {
      'Authorization': `Token ${token}`
    }
  });
  expect(newArticleResponse.status()).toEqual(201)

  await page.goto('https://conduit.bondaracademy.com')
  
  await expect(page.locator('.preview-link h1').first()).toContainText('Test title')
  await page.getByText('Test title').click()
  await page.getByRole('button', { name: 'Delete Article' }).first().click()
  await page.waitForResponse('https://conduit-api.bondaracademy.com/api/articles?limit=10&offset=0')
  await expect(page.locator('.preview-link h1').first()).not.toContainText('Test title')
});

test('Create article', async ({ page, request }) => {
  await page.goto('https://conduit.bondaracademy.com')

  await page.getByText('New Article').click()
  await page.getByRole('textbox', { name: 'Article Title' }).fill('Playwright API Testing')
  await page.getByRole('textbox', { name: 'What\'s this article about?' }).fill('This article is about testing APIs with Playwright')
  await page.getByRole('textbox', { name: 'Write your article (in markdown)' }).fill('Automate API testing with Playwright and TypeScript')
  await page.getByRole('button', { name: 'Publish Article' }).click()
  const createArticleResponse = await page.waitForResponse('https://conduit-api.bondaracademy.com/api/articles/')
  const articleResponseJSON = await createArticleResponse.json()
  const slugID = articleResponseJSON.article.slug

  await expect(page.locator('.article-page h1').first()).toContainText('Playwright API Testing')
  await page.getByText('Home').first().click()
  await expect(page.locator('.preview-link h1').first()).toContainText('Playwright API Testing')

  const token = authState.origins[0].localStorage[0].value

  const deleteArticleResponse = await request.delete(`https://conduit-api.bondaracademy.com/api/articles/${slugID}`, { //delete requests don't have body parameters
    headers: {
      'Authorization': `Token ${token}`
    }
  });
  expect(deleteArticleResponse.status()).toEqual(204)

});