# Configurações do Filter Tasks Planner
app:
    name: Filter Tasks Planner
    version: 1.0.0

observe:
    schedule: 300 # segundos
    file: C:\Users\gabri\OneDrive\Documentos\Projetos\Artificial\learning\automations\filter_tasks_planner\data\tasksplanner.json # arquivo para monitorar

others:
    tasks_excel: C:\Users\gabri\OneDrive\Documentos\Projetos\Artificial\learning\automations\filter_tasks_planner\data\Tasks Planner.xlsx
    tasks_moved: C:\Users\gabri\OneDrive\Documentos\Projetos\Artificial\learning\automations\filter_tasks_planner\data\changedbuckets.json
    tasks_new: C:\Users\gabri\OneDrive\Documentos\Projetos\Artificial\learning\automations\filter_tasks_planner\data\tasksnew.json

options:
    created: true
    modified: true

log:
    active: true
    mode: INFO # DEBUG, INFO, WARNING e ERROR
    path: C:\Users\gabri\OneDrive\Documentos\Projetos\Artificial\learning\automations\filter_tasks_planner\log\filter_tasks_planner.log